version: "3"

services:
  deploy:
    image: "instrumentisto/rsync-ssh"
    volumes:
      - .:/var/www
    working_dir: /var/www
    environment:
      deploy_key: $DEPLOY_KEY
    command: sh scripts/deploy.sh
