name: Continous Deployment 
on: 
    push:
    branches:
      - master

    jobs:
      deploy:
        steps:
          - name: Build and deploy application
            working-directory: website

            env:
                remote_key: ${{ secrets.deploy_key }}
                remote_host: ${{ secrets.deploy_host }}
                remote_user: ${{ secrets.deploy_user }}
                local_dir: "public/                    
                remote_dir: "/var/www/cabin/public/"

            run: |
                npm run build
                mkdir ~/.ssh
                echo "$remote_key" > ~/.ssh/gh_actions_key
                chmod 600 ~/.ssh/gh_actions_key 
                rsync -avzr --delete -e "ssh -i ~/.ssh/gh_actions_key -o StrictHostKeyChecking=no" ${local_dir} ${remote_user}@${remote_host}:${remote_dir}
