name: Update website
on: [push, repository_dispatch]

env:
  CI: true

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-node@v1
        with:
          node-version: "12.8.1"
      - uses: actions/checkout@v2

      - name: Install dependencies
        run: npm ci
        working-directory: website

      - name: Build CSS from less
        run: npm run build:css
        working-directory: website

      - name: Run tests
        run: npm run test
        working-directory: website

      - name: Build and deploy application
        working-directory: website
        run: |
          npm run build
          mkdir ~/.ssh
          echo "$DEPLOY_KEY" > ~/.ssh/gh_actions_key
          chmod 600 ~/.ssh/gh_actions_key 
          rsync -avz -e "ssh -i ~/.ssh/gh_actions_key -o StrictHostKeyChecking=no" public/ root@smestad.xyz:/var/www/cabin/public
        env:
          DEPLOY_KEY: ${{ secrets.deploy_key }}
