name: CI
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

env:
  CI: true
  
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/setup-node@v1
      with:
         node-version: "12.8.1"
    - uses: actions/checkout@v2

    - name: Install dependencies
      run: npm ci

    - name: Build CSS from less
      run: npm run build:css

    - name: Run tests
      run: npm run test

    - name: Build application
      run: npm run build

