name: Update website
on: [push, repository_dispatch]

env:
  CI: true

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-node@v1
        with:
          node-version: "12.8.1"
      - uses: actions/checkout@v2

      - name: Install dependencies
        run: npm ci
        working-directory: website

      - name: Build CSS from less
        run: npm run build:css
        working-directory: website

      - name: Run tests
        run: npm run test
        working-directory: website

      - name: Build application
        run: gatsby build
        working-directory: website

      - name: Deploy
        run: docker-compose run deploy
        if: github.ref == 'refs/heads/master'
        env:
          DEPLOY_KEY: ${{ secrets.deploy_key}}
